omp_lib = fullfile(matlabroot, 'bin', computer('arch'), 'libiomp5md.lib');

mex('-R2018a', ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'COMPFLAGS="$COMPFLAGS /openmp:llvm"', ...
    'LINKFLAGS="$LINKFLAGS /NODEFAULTLIB:libomp.lib /NODEFAULTLIB:vcomp.lib"', ...
    'SYM_aFSAI_compute.cpp', ...
    'compute_local_fsai.cpp', ...
    'cpt_afsai_coef.cpp', ...
    omp_lib);