% Get Homebrew Paths
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew. Make sure it is installed.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% Define the STATIC Library Path
% We link against libomp.a directly to embed it and hide it from MATLAB.
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end

fprintf('Linking statically against: %s\n', omp_static);

% Compile command for FilterComp_wrap
mex('-O', ...
    '-R2018a',...
    omp_inc, ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'CXXFLAGS="$CXXFLAGS -std=c++11 -O2 -Xpreprocessor -fopenmp -fPIC -mmacosx-version-min=15.0 -I./include/"', ...
    'LDFLAGS="$LDFLAGS -mmacosx-version-min=15.0 -O2"', ...
    'FilterComp_wrap.cpp', ...
    'FilterComp.cpp', ...
    'FilterComp_stripe.cpp', ...
    'abs_ri_heapsort.cpp', ...
    'bin_search.cpp', ...
    'ir_heapsort.cpp', ...
    omp_static); % <--- The Fix
