mex -O -R2018a FilterComp_wrap.cpp FilterComp.cpp ...
    FilterComp_stripe.cpp abs_ri_heapsort.cpp bin_search.cpp ...
    ir_heapsort.cpp ...
    COMPFLAGS="$COMPFLAGS -I./include/ /openmp:llvm" -lmwblas -lmwlapack
