mex -O -R2018a -I"./include/" FilterComp_wrap.cpp FilterComp.cpp ...
    FilterComp_stripe.cpp abs_ri_heapsort.cpp bin_search.cpp ...
    ir_heapsort.cpp ...
    COMPFLAGS="$COMPFLAGS /openmp" -lmwblas -lmwlapack
