mex -O FilterComp_wrap.cpp FilterComp.cpp FilterComp_stripe.cpp abs_ri_heapsort.cpp...
       bin_search.cpp ir_heapsort.cpp...
       CXXFLAGS="-I./include/ -std=c++11 -O2 -fopenmp -fPIC" LDFLAGS="-std=c++11...
       -fopenmp -O2 -z noexecstack" -lmwblas -lmwlapack

%!cp FilterComp_wrap.mexa64 ..
