mex -O -R2018a FilterComp_wrap.cpp FilterComp.cpp FilterComp_stripe.cpp abs_ri_heapsort.cpp...
       bin_search.cpp ir_heapsort.cpp...
       CXXFLAGS="-I./include/ -std=c++14 -O3 -fopenmp -fPIC" LDFLAGS="-std=c++14...
       -fopenmp -O3 -z noexecstack" -lmwblas -lmwlapack

%!cp FilterComp_wrap.mexa64 ..
