% Setup Paths for OpenMP (Homebrew)
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew. Make sure it is installed.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% Use Static Library to prevent MATLAB Runtime Crash
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end

mex('-O', ...
    '-R2018a',...
    omp_inc, ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'CXXFLAGS="$CXXFLAGS -std=c++11 -O2 -Xpreprocessor -fopenmp -mmacosx-version-min=15.0 -fPIC -I../Cpp_EMIN/include/ "', ...
    'LDFLAGS="$LDFLAGS -mmacosx-version-min=15.0 -O2"', ... 
    'EMIN_Prolong_compute.cpp', ...
    'apply_perm.cpp', ...
    'copy_Prol.cpp', ...
    'count_rowterms.cpp', ...
    'cpt_Trace_Acc.cpp', ...
    'ddot_par.cpp', ...
    'DebEnv.cpp', ...
    'DEFL_PCG.cpp', ...
    'DEFL_PCG_matfree.cpp', ...
    'dnrm2_par.cpp', ...
    'EMIN_ImpProl.cpp', ...
    'EMIN_matfree.cpp', ...
    'gather_B_dump.cpp', ...
    'gather_B_QR.cpp', ...
    'gather_B_Z.cpp', ...
    'gather_col.cpp', ...
    'gather_f.cpp', ...
    'gather_K.cpp', ...
    'KP_spmat.cpp', ...
    'LinvP_spmat.cpp', ...
    'load_Jacobi.cpp', ...
    'mkiat_Tglo.cpp', ...
    'mkiat_Tloc.cpp', ...
    'mult_K_col.cpp', ...
    'mult_K_matfree.cpp', ...
    'mvjcol.cpp', ...
    'NLSP_PCG.cpp', ...
    'Orth_Q.cpp', ...
    'print_Q.cpp', ...
    'print_Z.cpp', ...
    'Prol_add_Cnodes.cpp', ...
    'solve_RRQR.cpp', ...
    'spmatv_blk.cpp', ...
    'Transp_Patt.cpp', ...
    'UinvDP_spmat.cpp', ...
    'wrCSRmat.cpp', ...
    'Z_mult.cpp', ...
    'ZT_mult.cpp', ...
    omp_static); 

