% 1. Setup Paths for OpenMP (Homebrew)
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew. Make sure it is installed.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% CRITICAL FIX: Use Static Library to prevent MATLAB Runtime Crash
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end
fprintf('Linking statically against: %s\n', omp_static);

% 2. Setup Paths for GFortran (Homebrew)
% We need this because libICHOL.a depends on libgfortran
[s, gf_path] = system('dirname $(/opt/homebrew/bin/gfortran -print-file-name=libgfortran.dylib)');
if s ~= 0
    % Try generic command if explicit path fails
    [s, gf_path] = system('dirname $(gfortran -print-file-name=libgfortran.dylib)');
end
if s ~= 0
    error('Error: Could not find gfortran. Is GCC installed? (brew install gcc)');
end
gf_path = strtrim(gf_path);
fprintf('Found gfortran library at: %s\n', gf_path);

% 3. Check if libICHOL exists, build if missing
libFolder = '../Cpp_EMIN/ICHOL';
libFile = fullfile(libFolder, 'libICHOL.a');

if ~isfile(libFile)
    fprintf('libICHOL.a not found. Attempting to build...\n');
    [s, m_msg] = system(['export PATH=/opt/homebrew/bin:$PATH; make -C ' libFolder]);
    if s ~= 0
        disp(m_msg);
        error('Failed to build libICHOL.');
    end
    % Ensure Mac indexes the library
    system(['ranlib ' libFile]);
end

% 4. Compile Command
% Changes:
% - REMOVED '-lomp' and omp_lib (Dynamic linking causing crashes).
% - ADDED 'omp_static' at the end (Static linking).
% - Kept '-lgfortran' (Fortran must be dynamic).
% - Kept '-lICHOL'.
mex('-O', ...
    omp_inc, ...
    ['-L' gf_path], ...         % Path to gfortran libs
    ['-L' libFolder], ...       % Path to libICHOL.a
    '-lICHOL', ...              % Link Custom Lib
    '-lgfortran', ...           % Link Fortran Runtime
    '-lmwblas', ...
    '-lmwlapack', ...
    'CXXFLAGS="$CXXFLAGS -std=c++11 -O2 -Xpreprocessor -fopenmp -mmacosx-version-min=15.0 -fPIC -I../Cpp_EMIN/include/ -I../Cpp_EMIN/ICHOL"', ...
    'LDFLAGS="$LDFLAGS -Wl,-ld_classic -mmacosx-version-min=15.0 -O2"', ... 
    'EMIN_Prolong_compute.cpp', ...
    'apply_perm.cpp', ...
    'copy_Prol.cpp', ...
    'count_rowterms.cpp', ...
    'cpt_ichol_K.cpp', ...
    'cpt_Trace_Acc.cpp', ...
    'ddot_par.cpp', ...
    'DebEnv.cpp', ...
    'DEFL_PCG.cpp', ...
    'DEFL_PCG_matfree.cpp', ...
    'dnrm2_par.cpp', ...
    'EMIN_ImpProl.cpp', ...
    'EMIN_matfree.cpp', ...
    'gather_B_dump.cpp', ...
    'gather_B_QR.cpp', ...
    'gather_B_Z.cpp', ...
    'gather_col.cpp', ...
    'gather_f.cpp', ...
    'gather_K.cpp', ...
    'ichol_matfree.cpp', ...
    'icholRF_apply.cpp', ...
    'KP_spmat.cpp', ...
    'LinvP_spmat.cpp', ...
    'load_Jacobi.cpp', ...
    'mkiat_Tglo.cpp', ...
    'mkiat_Tloc.cpp', ...
    'mult_K_col.cpp', ...
    'mult_K_matfree.cpp', ...
    'mvjcol.cpp', ...
    'NLSP_PCG.cpp', ...
    'Orth_Q.cpp', ...
    'print_Q.cpp', ...
    'print_Z.cpp', ...
    'Prol_add_Cnodes.cpp', ...
    'solve_RRQR.cpp', ...
    'spmatv_blk.cpp', ...
    'Transp_Patt.cpp', ...
    'UinvDP_spmat.cpp', ...
    'wrCSRmat.cpp', ...
    'Z_mult.cpp', ...
    'ZT_mult.cpp', ...
    omp_static); % <--- The Fix (Static OpenMP)
