mex -O EMIN_Prolong_compute.cpp EMIN_ImpProl.cpp EMIN_matfree.cpp DEFL_PCG.cpp NLSP_PCG.cpp...
       apply_perm.cpp load_Jacobi.cpp mult_K_col.cpp mult_K_matfree.cpp DEFL_PCG_matfree.cpp...
       copy_Prol.cpp count_rowterms.cpp Z_mult.cpp ZT_mult.cpp gather_B_Z.cpp print_Z.cpp...
       cpt_ichol_K.cpp ddot_par.cpp DebEnv.cpp dnrm2_par.cpp gather_B_QR.cpp ichol_matfree.cpp...
       gather_col.cpp gather_K.cpp icholRF_apply.cpp mkiat_Tglo.cpp mkiat_Tloc.cpp...
       mvjcol.cpp Orth_Q.cpp print_Q.cpp Prol_add_Cnodes.cpp spmatv_blk.cpp...
       cpt_Trace_Acc.cpp Transp_Patt.cpp wrCSRmat.cpp gather_f.cpp KP_spmat.cpp...
       solve_RRQR.cpp...
       CXXFLAGS="-I../Cpp_EMIN/include/ -I../Cpp_EMIN/ICHOL -std=c++11 -O0 -g -fopenmp -Wall -DPRINT -fPIC"...
       LDFLAGS="-L. -std=c++11  -fopenmp -O0 -g" -lmwblas -lmwlapack -lICHOL
