% Get Homebrew Paths
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% Define the STATIC Library Path
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end

% Determine host macOS deployment target
[status, ver_str] = system('sw_vers -productVersion');
if status == 0
    mac_ver = strtrim(ver_str);
else
    mac_ver = '15.0';
end
ver_flag = ['-mmacosx-version-min=' mac_ver];

% Compile
mex('-silent', ...
    '-O', ...
    '-R2018a',...
    omp_inc, ...
    '-lmwblas', ...
    '-lmwlapack', ...
    ['CXXFLAGS="$CXXFLAGS -std=c++14 -Xpreprocessor -fopenmp -ffast-math -fPIC ' ver_flag '"'], ...
    ['LDFLAGS="$LDFLAGS ' ver_flag '"'], ...
    'sam_adaptive_left_mex.cpp', ...
    'cpt_sam_adaptive_left.cpp', ...
    'qr_functions.cpp', ...
    'find_stuff.cpp', ...
    'cpt_resRho.cpp', ...
    omp_static);
