mex -O -R2018a ...
   sam_adaptive_left_mex.cpp cpt_sam_adaptive_left.cpp ...
   qr_functions.cpp find_stuff.cpp cpt_resRho.cpp ...
   CXXFLAGS="$CXXFLAGS -std=c++11 -fopenmp -ffast-math -fPIC" ...
   LDFLAGS="$LDFLAGS -fopenmp -z noexecstack" ...
   -lmwblas -lmwlapack
