% Locate Intel OpenMP runtime shipped with MATLAB
omp_lib = fullfile(matlabroot, 'bin', computer('arch'), 'libiomp5md.lib');
if ~isfile(omp_lib)
    error('OpenMP library not found at: %s', omp_lib);
end

% Compile
mex('-O', ...
    '-R2018a', ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'COMPFLAGS="$COMPFLAGS /std:c++14 /openmp:llvm /fp:fast"', ...
    'LINKFLAGS="$LINKFLAGS /NODEFAULTLIB:libomp.lib /NODEFAULTLIB:vcomp.lib"', ...
    'sam_adaptive_left_mex.cpp', ...
    'cpt_sam_adaptive_left.cpp', ...
    'qr_functions.cpp', ...
    'find_stuff.cpp', ...
    'cpt_resRho.cpp', ...
    omp_lib);