clc;
clear;
close all;

list = {'sources/Preconditioner/AMG/smoother/MEX_SYM_AFSAI/', ...
        'sources/Preconditioner/AMG/smoother/MEX_NSY_RFSAI/', ...
        'sources/Preconditioner/AMG/prolong/MEX_HYBC_prol/', ...
        'sources/Preconditioner/AMG/prolong/MEX_CLAS_prol/', ...
        'sources/Preconditioner/AMG/prolong/MEX_BAMG_Prol/', ...
        'sources/Preconditioner/AMG/prolong/MEX_EXTI_Prol/', ...
        'sources/Preconditioner/AMG/prolong/EMIN/MEX_EMIN/', ...
        'sources/Preconditioner/AMG/filter/MEX_CLev_Filter/', ...
        'sources/Preconditioner/AMG/filter/MEX_Prol_Filter/'};

home = pwd;
for folder = list
    fprintf('Compiling MEX files in %s\n', folder{1});
    cd(folder{1});
    if strcmp(computer('arch'),'maca64')
       compileMac
    else
       compile
    end
    cd(home);
end
