mex -O cpt_Prolongation_EXTI.cpp EXTI_prolongation.cpp ProlStripe_EXTI.cpp...
       ONELP_ProlStripe_EXTI.cpp ir_heapsort.cpp...
       TWOLP_ProlStripe_EXTI.cpp CFLAGS="-I./include/ -std=c++11...
       -O2 -fopenmp -fPIC" LDFLAGS="-std=c++11 -fopenmp -O2 -z noexecstack"

%!cp cpt_Prolongation_EXTI.mexa64 ..
