mex -O -R2018a cpt_Prolongation_EXTI.cpp EXTI_prolongation.cpp ProlStripe_EXTI.cpp...
       ONELP_ProlStripe_EXTI.cpp ir_heapsort.cpp TWOLP_ProlStripe_EXTI.cpp ...
       COMPFLAGS="$COMPFLAGS -I./include/ /openmp:llvm" 
