mex -O -R2018a cpt_Prolongation_EXTI.cpp EXTI_prolongation.cpp ProlStripe_EXTI.cpp...
       ONELP_ProlStripe_EXTI.cpp ir_heapsort.cpp...
       TWOLP_ProlStripe_EXTI.cpp CFLAGS="-I./include/ -std=c++14...
       -O2 -fopenmp -fPIC" LDFLAGS="-std=c++14 -fopenmp -O2 -z noexecstack"
