omp_lib = fullfile(matlabroot, 'bin', computer('arch'), 'libiomp5md.lib');

mex('-O', ...
    '-R2018a', ...
    'COMPFLAGS="$COMPFLAGS -I./include/ /openmp:llvm"', ...
    'LINKFLAGS="$LINKFLAGS /NODEFAULTLIB:libomp.lib /NODEFAULTLIB:vcomp.lib"', ...
    'cpt_Prolongation_EXTI.cpp', ...
    'EXTI_prolongation.cpp', ...
    'ProlStripe_EXTI.cpp', ...
    'ONELP_ProlStripe_EXTI.cpp', ...
    'ir_heapsort.cpp', ...
    'TWOLP_ProlStripe_EXTI.cpp', ...
    omp_lib);