omp_lib = fullfile(matlabroot, 'bin', computer('arch'), 'libiomp5md.lib');

mex('-R2018a', ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'COMPFLAGS="$COMPFLAGS /openmp:llvm"', ...
    'LINKFLAGS="$LINKFLAGS /NODEFAULTLIB:libomp.lib /NODEFAULTLIB:vcomp.lib"', ...
    'NSY_rFSAI_compute.cpp', ...
    'Compute_nsy_rfsai.cpp', ...
    'KapGrad_NSY.cpp', ...
    'SymmetrizePattern.cpp', ...
    'compress_nsy_fsai.cpp', ...
    'cpt_nsy_rfsai.cpp', ...
    'extract_diag.cpp', ...
    'gather_fullsys.cpp', ...
    'heapsort.cpp', ...
    'merge_row_patt.cpp', ...
    'ri_sortsplit_nsy.cpp', ...
    'transpose.cpp', ...
    'DEBUG.cpp', ...
    'wrCSRmat.cpp', ...
    omp_lib);