clc;
clear;
close all;

list = {'smoother/MEX_SYM_AFSAI/', ...
        'smoother/MEX_NSY_RFSAI/', ...
        'prolong/MEX_HYBC_prol/', ...
        'prolong/MEX_CLAS_prol/', ...
        'prolong/MEX_BAMG_Prol/', ...
        'prolong/MEX_EXTI_Prol/', ...
        'prolong/EMIN/MEX_EMIN/', ...
        'filter/MEX_CLev_Filter/', ...
        'filter/MEX_Prol_Filter/'};

home = pwd;
for folder = list
    fprintf('Compiling MEX files in %s\n', folder{1});
    cd(folder{1});
    if computer('arch') == 'maca64'
       compileMac
    else
       compile
    end
    cd(home);
end
