% 1. Get Homebrew Paths
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew. Make sure it is installed.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% 2. Define the STATIC Library Path
% We link against the .a file directly to hide OpenMP from MATLAB
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end

fprintf('Linking statically against: %s\n', omp_static);

% 3. Compile command for cpt_Prolongation_BAMG
% Changes:
% - Removed '-L...' and '-lomp' (Dynamic linking).
% - Added 'omp_static' (Static linking) at the end.
mex('-O', ...
    omp_inc, ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'CXXFLAGS="$CXXFLAGS -std=c++11 -O2 -Xpreprocessor -fopenmp -fPIC -mmacosx-version-min=15.0 -I./include/"', ...
    'LDFLAGS="$LDFLAGS -Wl,-ld_classic -mmacosx-version-min=15.0 -O2"', ...
    'cpt_Prolongation_BAMG.cpp', ...
    'BAMG.cpp', ...
    'ProlStripe_BAMG.cpp', ...
    'Reduce_IntSet.cpp', ...
    'linsol_error.cpp', ...
    'Apply_HouHol_Rot.cpp', ...
    'maxVol.cpp', ...
    'add_new_neighs.cpp', ...
    'get_cond.cpp', ...
    'maxVol_inner.cpp', ...
    'DebEnv.cpp', ...
    'backsolve.cpp', ...
    'heapsort.cpp', ...
    'mk_HouHolVec.cpp', ...
    'check_neigh_cond.cpp', ...
    'move_row_front.cpp', ...
    omp_static); % <--- The fix
