mex -O -R2018a cpt_Prolongation_Classical.cpp Classical_prolongation.cpp ...
       ProlStripe_Classical.cpp ir_heapsort.cpp ...
       CFLAGS="-I./include/ -std=c++14 -O2 -fopenmp -fPIC" ... 
       LDFLAGS="-std=c++14 -fopenmp -O2 -z noexecstack"
