omp_lib = fullfile(matlabroot, 'bin', computer('arch'), 'libiomp5md.lib');

mex('-O', ...
    '-R2018a', ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'COMPFLAGS="$COMPFLAGS -I./include/ /openmp:llvm"', ...
    'LINKFLAGS="$LINKFLAGS /NODEFAULTLIB:libomp.lib /NODEFAULTLIB:vcomp.lib"', ...
    'cpt_Prolongation_Classical.cpp', ...
    'Classical_prolongation.cpp', ...
    'ProlStripe_Classical.cpp', ...
    'ir_heapsort.cpp', ...
    omp_lib);