omp_lib = fullfile(matlabroot, 'bin', computer('arch'), 'libiomp5md.lib');

mex('-O', ...
    '-R2018a', ...
    'COMPFLAGS="$COMPFLAGS -I./include/ /openmp:llvm"', ...
    'LINKFLAGS="$LINKFLAGS /NODEFAULTLIB:libomp.lib /NODEFAULTLIB:vcomp.lib"', ...
    'cpt_Prolongation_HybridClas.cpp', ...
    'HybridClas_prolongation.cpp', ...
    'ProlStripe_HybridClas.cpp', ...
    'ir_heapsort.cpp', ...
    'find_bad_FS.cpp', ...
    'find_dist2CC.cpp', ...
    omp_lib);