mex -O -R2018a cpt_Prolongation_HybridClas.cpp HybridClas_prolongation.cpp ...
       ProlStripe_HybridClas.cpp ir_heapsort.cpp ...
       find_bad_FS.cpp find_dist2CC.cpp ...
       COMPFLAGS="$COMPFLAGS -I./include/ /openmp"
