% Get Homebrew Paths
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew. Make sure it is installed.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% Define the STATIC Library Path
% We link libomp.a directly to prevent conflicts with MATLAB's internal OpenMP.
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end

fprintf('Linking statically against: %s\n', omp_static);

% Compile command for cpt_Prolongation_EXTI
mex('-O', ...
    '-R2018a',...
    omp_inc, ...
    'CXXFLAGS="$CXXFLAGS -std=c++11 -O2 -Xpreprocessor -fopenmp -fPIC -mmacosx-version-min=15.0 -I./include/"', ...
    'LDFLAGS="$LDFLAGS -mmacosx-version-min=15.0 -O2"', ...
    'cpt_Prolongation_EXTI.cpp', ...
    'EXTI_prolongation.cpp', ...
    'ProlStripe_EXTI.cpp', ...
    'ONELP_ProlStripe_EXTI.cpp', ...
    'ir_heapsort.cpp', ...
    'TWOLP_ProlStripe_EXTI.cpp', ...
    omp_static); % <--- The Fix
