clc
% Get Homebrew Paths
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% Define the STATIC Library Path
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end
fprintf('Linking statically against: %s\n', omp_static);

% Compile
mex('-O', ...
    '-R2018a',...
    omp_inc, ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'CXXFLAGS="$CXXFLAGS -std=c++11 -Xpreprocessor -fopenmp -fPIC -mmacosx-version-min=15.0"', ...
    'LDFLAGS="$LDFLAGS -mmacosx-version-min=15.0"', ...
    'sam_adaptive_left_mex.cpp', ...
    'cpt_sam_adaptive_left.cpp', ...
    'qr_functions.cpp', ...
    'find_stuff.cpp', ...
    'cpt_resRho.cpp', ...
    omp_static);