% 1. Get Homebrew Paths
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew. Make sure it is installed.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% 2. Define the STATIC Library Path
% We link against libomp.a directly to embed it and hide it from MATLAB.
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end

fprintf('Linking statically against: %s\n', omp_static);

% 3. Compile command for cpt_Prolongation_HybridClas
% Changes:
% - Removed '-L' and '-lomp' (Dynamic linking).
% - Added 'omp_static' (Static linking) to the end.
mex('-O', ...
    omp_inc, ...
    'CXXFLAGS="$CXXFLAGS -std=c++11 -O2 -Xpreprocessor -fopenmp -mmacosx-version-min=15.0 -fPIC -I./include/"', ...
    'LDFLAGS="$LDFLAGS -Wl,-ld_classic -mmacosx-version-min=15.0 -O2"', ...
    'cpt_Prolongation_HybridClas.cpp', ...
    'HybridClas_prolongation.cpp', ...
    'ProlStripe_HybridClas.cpp', ...
    'ir_heapsort.cpp', ...
    'find_bad_FS.cpp', ...
    'find_dist2CC.cpp', ...
    omp_static); % <--- The Fix
