% Get Homebrew Paths
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew. Make sure it is installed.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% Define the STATIC Library Path
% Link against libomp.a directly to embed it and hide it from MATLAB.
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end

fprintf('Linking statically against: %s\n', omp_static);

% Compile command for NSY_rFSAI_compute
mex('-O', ...
    '-R2018a',...
    omp_inc, ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'CXXFLAGS="$CXXFLAGS -std=c++11 -O2 -Xpreprocessor -fopenmp -fPIC -mmacosx-version-min=15.0"', ...
    'LDFLAGS="$LDFLAGS -mmacosx-version-min=15.0 -O2"', ...
    'NSY_rFSAI_compute.cpp', ...
    'Compute_nsy_rfsai.cpp', ...
    'KapGrad_NSY.cpp', ...
    'SymmetrizePattern.cpp', ...
    'compress_nsy_fsai.cpp', ...
    'cpt_nsy_rfsai.cpp', ...
    'extract_diag.cpp', ...
    'gather_fullsys.cpp', ...
    'heapsort.cpp', ...
    'merge_row_patt.cpp', ...
    'ri_sortsplit_nsy.cpp', ...
    'transpose.cpp', ...
    'DEBUG.cpp', ...
    'wrCSRmat.cpp', ...
    omp_static); 
