libFolder = '../Cpp_EMIN/ICHOL';
libFile = fullfile(libFolder, 'libICHOL.a');

if ~isfile(libFile)
    [s, m_msg] = system(['make -C ' libFolder]);
    if s ~= 0
        disp(m_msg);
        error('Failed to build libICHOL.');
    end
end

mex -O EMIN_Prolong_compute.cpp apply_perm.cpp copy_Prol.cpp count_rowterms.cpp...
       cpt_ichol_K.cpp cpt_Trace_Acc.cpp ddot_par.cpp DebEnv.cpp DEFL_PCG.cpp...
       DEFL_PCG_matfree.cpp dnrm2_par.cpp EMIN_ImpProl.cpp EMIN_matfree.cpp...
       gather_B_dump.cpp gather_B_QR.cpp gather_B_Z.cpp gather_col.cpp gather_f.cpp...
       gather_K.cpp ichol_matfree.cpp icholRF_apply.cpp KP_spmat.cpp LinvP_spmat.cpp...
       load_Jacobi.cpp mkiat_Tglo.cpp mkiat_Tloc.cpp mult_K_col.cpp mult_K_matfree.cpp...
       mvjcol.cpp NLSP_PCG.cpp Orth_Q.cpp print_Q.cpp print_Z.cpp Prol_add_Cnodes.cpp...
       solve_RRQR.cpp spmatv_blk.cpp Transp_Patt.cpp UinvDP_spmat.cpp wrCSRmat.cpp...
       Z_mult.cpp ZT_mult.cpp...
       CXXFLAGS="-I../Cpp_EMIN/include/ -I../Cpp_EMIN/ICHOL -std=c++11 -O2 -fopenmp -fPIC"...
       LDFLAGS="-L. -std=c++11  -fopenmp -O2 -z noexecstack" -lmwblas -lmwlapack -lICHOL
