mex -O -R2018a sam_preprocess_left_mex.cpp sam_preprocess_left.cpp ...
       CXXFLAGS="-std=c++14 -O2 -fopenmp -fPIC" ...
       LDFLAGS="-std=c++14 -fopenmp -O2 -z noexecstack"

mex -O -R2018a sam_compute_left_mex.cpp sam_compute_left.cpp ...
       CXXFLAGS="-std=c++14 -O2 -fopenmp -fPIC" ...
       LDFLAGS="-std=c++14 -fopenmp -O2 -z noexecstack"
