mex -O -R2018a sam_preprocess_left_mex.cpp ...
       CXXFLAGS="-I./include/ -std=c++11 -O2 -fopenmp -fPIC" LDFLAGS="-std=c++11...
       -fopenmp -O2 -z noexecstack" -lmwblas -lmwlapack

mex -O -R2018a sam_compute_left_mex.cpp ...
       CXXFLAGS="-I./include/ -std=c++11 -O2 -fopenmp -fPIC" LDFLAGS="-std=c++11...
       -fopenmp -O2 -z noexecstack" -lmwblas -lmwlapack

