mex -O -R2018a sam_preprocess_left_mex.cpp ...
       CXXFLAGS="-I./include/ -std=c++14 -O3 -fopenmp -fPIC" LDFLAGS="-std=c++14...
       -fopenmp -O3 -z noexecstack" -lmwblas -lmwlapack

mex -O -R2018a sam_compute_left_mex.cpp ...
       CXXFLAGS="-I./include/ -std=c++14 -O3 -fopenmp -fPIC" LDFLAGS="-std=c++14...
       -fopenmp -O3 -z noexecstack" -lmwblas -lmwlapack

