omp_lib = fullfile(matlabroot, 'bin', computer('arch'), 'libiomp5md.lib');

mex('-O', ...
    '-R2018a', ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'COMPFLAGS="$COMPFLAGS -I./include/ /openmp:llvm"', ...
    'LINKFLAGS="$LINKFLAGS /NODEFAULTLIB:libomp.lib /NODEFAULTLIB:vcomp.lib"', ...
    'FilterProl_wrap.cpp', ...
    'FilterProl.cpp', ...
    'FilterProl_stripe.cpp', ...
    'abs_ri_heapsort.cpp', ...
    'ir_heapsort.cpp', ...
    omp_lib);