mex -O -R2018a FilterProl_wrap.cpp FilterProl.cpp FilterProl_stripe.cpp abs_ri_heapsort.cpp...
       ir_heapsort.cpp...
       COMPFLAGS="$COMPFLAGS -I./include/ /openmp"...
       -lmwblas -lmwlapack
