mex -O -R2018a FilterProl_wrap.cpp FilterProl.cpp FilterProl_stripe.cpp abs_ri_heapsort.cpp...
       ir_heapsort.cpp...
       CXXFLAGS="-I./include/ -std=c++14 -O3 -fopenmp -fPIC" LDFLAGS="-std=c++14...
       -fopenmp -O3 -z noexecstack" -lmwblas -lmwlapack
