mex -O -R2018a FilterProl_wrap.cpp FilterProl.cpp FilterProl_stripe.cpp abs_ri_heapsort.cpp...
       ir_heapsort.cpp...
       CXXFLAGS="-I./include/ -std=c++11 -O2 -fopenmp -fPIC" LDFLAGS="-std=c++11...
       -fopenmp -O2 -z noexecstack" -lmwblas -lmwlapack
