mex -O -R2018a cpt_Prolongation_BAMG.cpp BAMG.cpp ProlStripe_BAMG.cpp Reduce_IntSet.cpp...
       linsol_error.cpp Apply_HouHol_Rot.cpp maxVol.cpp add_new_neighs.cpp...
       get_cond.cpp maxVol_inner.cpp DebEnv.cpp backsolve.cpp heapsort.cpp...
       mk_HouHolVec.cpp check_neigh_cond.cpp move_row_front.cpp...
       CXXFLAGS="-I./include/ -std=c++14 -O2 -fopenmp -fPIC" LDFLAGS="-std=c++14...
       -fopenmp -O2 -z noexecstack" -lmwblas -lmwlapack
