% Get Homebrew Paths
[status, cmdout] = system('/opt/homebrew/bin/brew --prefix libomp');
if status ~= 0
    error('Error: Could not find libomp via Homebrew. Make sure it is installed.');
end
basePath = strtrim(cmdout);
omp_inc = ['-I' fullfile(basePath, 'include')];

% Define the STATIC Library Path
% We link against the .a file directly to hide OpenMP from MATLAB
omp_static = fullfile(basePath, 'lib', 'libomp.a');
if ~isfile(omp_static)
    error('Static library libomp.a not found at %s.', omp_static);
end

% Determine host macOS deployment target
[status, ver_str] = system('sw_vers -productVersion');
if status == 0
    mac_ver = strtrim(ver_str);
else
    mac_ver = '15.0';
end
ver_flag = ['-mmacosx-version-min=' mac_ver];

% Compile command for cpt_Prolongation_BAMG
mex('-silent', ...
    '-O', ...
    '-R2018a',...
    omp_inc, ...
    '-lmwblas', ...
    '-lmwlapack', ...
    ['CXXFLAGS="$CXXFLAGS -std=c++14 -O2 -Xpreprocessor -fopenmp -fPIC ' ver_flag ' -I./include/"'], ...
    ['LDFLAGS="$LDFLAGS ' ver_flag ' -O2"'], ...
    'cpt_Prolongation_BAMG.cpp', ...
    'BAMG.cpp', ...
    'ProlStripe_BAMG.cpp', ...
    'Reduce_IntSet.cpp', ...
    'linsol_error.cpp', ...
    'Apply_HouHol_Rot.cpp', ...
    'maxVol.cpp', ...
    'add_new_neighs.cpp', ...
    'get_cond.cpp', ...
    'maxVol_inner.cpp', ...
    'DebEnv.cpp', ...
    'backsolve.cpp', ...
    'heapsort.cpp', ...
    'mk_HouHolVec.cpp', ...
    'check_neigh_cond.cpp', ...
    'move_row_front.cpp', ...
    omp_static); 
