mex -O -R2018a cpt_Prolongation_BAMG.cpp BAMG.cpp ProlStripe_BAMG.cpp Reduce_IntSet.cpp...
       linsol_error.cpp Apply_HouHol_Rot.cpp maxVol.cpp add_new_neighs.cpp...
       get_cond.cpp maxVol_inner.cpp DebEnv.cpp backsolve.cpp heapsort.cpp...
       mk_HouHolVec.cpp check_neigh_cond.cpp move_row_front.cpp...
       COMPFLAGS="$COMPFLAGS -I./include/ /openmp:llvm" ...
       -lmwblas -lmwlapack
