% Define MATLAB's internal Intel OpenMP import library
omp_lib = fullfile(matlabroot, 'bin', computer('arch'), 'libiomp5md.lib');

% Compile command
mex('-O', ...
    '-R2018a', ...
    '-lmwblas', ...
    '-lmwlapack', ...
    'COMPFLAGS="$COMPFLAGS -I./include/ /openmp:llvm"', ...
    'LINKFLAGS="$LINKFLAGS /NODEFAULTLIB:libomp.lib /NODEFAULTLIB:vcomp.lib"', ...
    'cpt_Prolongation_BAMG.cpp', ...
    'BAMG.cpp', ...
    'ProlStripe_BAMG.cpp', ...
    'Reduce_IntSet.cpp', ...
    'linsol_error.cpp', ...
    'Apply_HouHol_Rot.cpp', ...
    'maxVol.cpp', ...
    'add_new_neighs.cpp', ...
    'get_cond.cpp', ...
    'maxVol_inner.cpp', ...
    'DebEnv.cpp', ...
    'backsolve.cpp', ...
    'heapsort.cpp', ...
    'mk_HouHolVec.cpp', ...
    'check_neigh_cond.cpp', ...
    'move_row_front.cpp', ...
    omp_lib);